# Generated by Django 3.2.7 on 2025-07-17 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devicewebapp', '0002_alter_userprofileinfo_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user_img',
        ),
        migrations.DeleteModel(
            name='DeviceProfileInfo',
        ),
    ]
